styles/styles.css

Fix #8
Test URLs:
- Before: https://main--stericycle-shared--aemsites.aem.page/drafts/janlucaa/button-styles
- After: https://issue-8--stericycle-shared--aemsites.aem.page/drafts/janlucaa/button-styles

Update button styles

---

blocks/header/header.css

Temporarily hiding nav last section, nav design in progress on branch issue-20
Test URLs:
- Before: https://main--shredit--aemsites.aem.page/en-us
- After: https://tmp-nav-hide--stericycle-shared--aemsites.aem.page/en-us

chore: hide last nav div

---

blocks/footer/footer.css
styles/styles.css

Resolve #29
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/drafts/janlucaa/list-styles
- After: https://issue-29--shredit--stericycle.aem.page/drafts/janlucaa/list-styles
- After: https://issue-29--stericycle-shared--aemsites.hlx.page/drafts/janlucaa/list-styles

Add additional list styles

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js
styles/styles.css

Resolve #44
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/drafts/janlucaa/carousel
- After: 
- https://issue-44--shredit--stericycle.aem.page/drafts/janlucaa/carousel
- https://issue-44--stericycle-shared--aemsites.aem.page/drafts/janlucaa/carousel

Add carousel block

---

styles/styles.css

Test URLs:
- Before: https://main--shredit--stericycle.aem.page/
- After: 
- https://fix-section-widths--shredit--stericycle.aem.page/
- https://fix-section-widths--stericycle-shared--aemsites.aem.page/

revert breaking style changes

---

blocks/header/header.css
blocks/header/header.js

Fix #55 
See URL - https://issue-55--shredit--stericycle.aem.page/en-us for latest changes.
Test URLs:
Before: https://main--shredit--stericycle.aem.page/en-us
After: https://issue-55--stericycle-shared--aemsites.aem.page/en-us

chore: nested mobile menu structure and styling

---

blocks/quote/quote.css
blocks/quote/quote.js

Resolve #61
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/drafts/janlucaa/locations/location-type-1
- After: 
- https://issue-61--shredit--stericycle.aem.page/drafts/janlucaa/locations/location-type-1
- https://issue-61--stericycle-shared--aemsites.aem.page/drafts/janlucaa/locations/location-type-1

Add quote block

---

scripts/scripts.js

Fix #59
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/
- After: 
- https://issue-59--shredit--stericycle.aem.page/
- https://issue-59--stericycle-shared--aemsites.aem.page/

Minor improvement to hero auto-blocking

---

blocks/columns/columns.css
blocks/faq/faq.css
blocks/featuretable/featuretable.css
blocks/flip-cards/flip-cards.css
styles/styles.css

Fix #60 
Test URLs:
- Before: [https://main--shredit--stericycle.aem.page/en-us](https://main--shredit--stericycle.aem.page/en-us/blog/data-security-ways-to-protect-yourself-at-tax-time)
- After: 
- [https://60-fix-block-content-width-issue--shredit--stericycle.aem.page/en-us/blog/data-security-ways-to-protect-yourself-at-tax-time ](https://60-fix-block-content-width-issue--shredit--stericycle.aem.page/en-us/blog/data-security-ways-to-protect-yourself-at-tax-time)
- [https://60-fix-block-content-width-issue--stericycle-shared--aemsites.aem.page/en-us](https://60-fix-block-content-width-issue--stericycle-shared--aemsites.aem.page/en-us)

Fix issue related to the block content width

---

blocks/video/video.css
blocks/video/video.js

Fix #65 
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/en-us/resource-center/videos/decluttering-your-workspace
- After: 
- https://wistia-embeds--shredit--stericycle.aem.page/en-us/resource-center/videos/decluttering-your-workspace
- https://wistia-embeds--stericycle-shared--aemsites.aem.page/en-us/resource-center/videos/decluttering-your-workspace

enable wistia embeds

---

blocks/paginated-list/paginated-list.css
blocks/paginated-list/paginated-list.js
scripts/scripts.js

Fix #79 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/about/press-releases
- https://www.shredit.com/en-us/about/press-releases
- After: 
- https://79-press-room--shredit--stericycle.aem.page/en-us/about/press-releases
- https://79-press-room--stericycle-shared--aemsites.aem.page/en-us/about/press-releases

79 press room

---

blocks/columns/columns.css
blocks/columns/columns.js

Fix #72 
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/shredding-events/community-shred-events-resources
- After: 
- https://downloadable-columns--shredit--stericycle.aem.page/en-us/secure-shredding-services/shredding-events/community-shred-events-resources
- https://downloadable-columns--stericycle-shared--aemsites.aem.page/en-us/secure-shredding-services/shredding-events/community-shred-events-resources

columns with downloadable files

---

blocks/header/header.css
styles/styles.css

Fix 
Test URLs:
- After: 
- https://cls-issue--shredit--stericycle.aem.live/en-us
- https://cls-issue--stericycle-shared--aemsites.aem.live/en-us

CLS issue header

---

blocks/header/header.css
blocks/header/header.js
blocks/hero/hero.css
styles/styles.css

Fix #89 #87 
Test URLs:
- After: 
- https://issue-89--shredit--stericycle.aem.live/en-us
- https://issue-89--stericycle-shared--aemsites.aem.live/en-us

Header styling improved

---

blocks/columns/columns.css
blocks/columns/columns.js

Fix #93 
Test URLs:
- Before: https://main--shredit--stericycle.aem.live/drafts/piyush/en-us
- After: 
- https://column-correction--shredit--stericycle.aem.live/drafts/piyush/en-us
- https://column-correction--stericycle-shared--aemsites.aem.live/drafts/piyush/en-us

Columns changes wrt to home page

---

blocks/header/header.css

Fix #86 
Test URLs:
- After: 
- https://header-change--shredit--stericycle.aem.live/en-us
- https://header-change--stericycle-shared--aemsites.aem.live/en-us

Header Hover Changes

---

scripts/scripts.js

Fix #116 
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/en-us/blog/surprising-ways-to-prevent-occupational-fraud
- After: 
- https://116-sensible--shredit--stericycle.aem.page/en-us/blog/surprising-ways-to-prevent-occupational-fraud
- https://116-sensible--stericycle-shared--aemsites.aem.page/en-us/blog/surprising-ways-to-prevent-occupational-fraud

related blog fill

---

scripts/scripts.js
styles/styles.css

Fix #82
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/en-us/service-locations/huntsville
- After: 
- [https://82-section-image-text--shredit--stericycle.aem.page/en-us/service-locations/huntsville](https://82-section-image-text--shredit--stericycle.aem.page/en-us/service-locations/huntsville)
- [https://82-section-image-text--stericycle-shared--aemsites.aem.page/en-us/service-locations/huntsville](https://82-section-image-text--stericycle-shared--aemsites.aem.page/en-us/service-locations/huntsville)

Add Section Styles for the service location pages

---

scripts/ffetch.js

Fix #118 
Test URLs:
- After: 
- https://common-query-json--shredit--stericycle.aem.live/en-us
- https://common-query-json--stericycle-shared--aemsites.aem.live/en-us

Common query json

---

blocks/header/header.css
blocks/header/header.js

Fix #
Test URLs:
- After: 
- https://header-imp-changes--shredit--stericycle.aem.live/en-us
- https://header-imp-changes--stericycle-shared--aemsites.aem.live/en-us

Some other header important changes

---

blocks/flip-cards/flip-cards.js

Fix #101 
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/en-us/about
- After: 
- https://flip-cards--shredit--stericycle.aem.page/en-us/about
- https://flip-cards--stericycle-shared--aemsites.aem.page/en-us/about

fetch flip card details dynamically

---

blocks/columns/columns.js
blocks/text/text.css
scripts/dom-helpers.js
scripts/scripts.js
styles/styles.css
templates/services/services.css

Fix #120 
Test URLs:
- Before: https://main--shredit--stericycle.aem.page/drafts/piyush/columns-border-top
- After: 
- https://column-back-image--shredit--stericycle.aem.live/drafts/piyush/columns-border-top
- https://column-back-image--stericycle-shared--aemsites.aem.live/drafts/piyush/columns-border-top

Template added for services page and columns handling

---

.github/pull_request_template.md
blocks/columns/columns.css
blocks/columns/columns.js
blocks/flip-cards/flip-cards.css
blocks/flip-cards/flip-cards.js
styles/styles.css

Fix #151
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services
- https://www.shredit.com/en-us/secure-shredding-services
- After: 
- https://150-misc-marketing-page-fixes--shredit--stericycle.aem.live/en-us/secure-shredding-services

misc changes to support marketing page building

---

blocks/icon-list/icon-list.css
blocks/icon-list/icon-list.js
tools/importer/svgs.js

Fix #165 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/hard-drive-destruction
- After: 
- https://165-icon-list--shredit--stericycle.aem.live/en-us/secure-shredding-services/hard-drive-destruction

icon list block

---

styles/styles.css

fix #169 
Test URLs:
- Before: 
- https://main--stericycle-shared--aemsites.aem.page/en-us/who-we-serve/insurance
- After: 
- https://fix-triangle-lists--stericycle-shared--aemsites.aem.page/en-us/who-we-serve/insurance

fix triangle list

---

blocks/icon-list/icon-list.css
styles/styles.css

Fix #171 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/paper-shredding-services
- After: 
-   - https://fix-icon-list-txt--shredit--stericycle.aem.page/en-us/secure-shredding-services/paper-shredding-services

make icon-list plain have no background

---

styles/styles.css

Fix #175 #173 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/mobile-shredding
- After: 
- https://add-column-with-icon-list--stericycle-shared--aemsites.aem.page/en-us/secure-shredding-services/mobile-shredding

adds column with navy background

---

tools/importer/service-location-data-fetcher.html
tools/importer/service-location-data.json
tools/importer/service-location.js

Fix 
Test URLs:
- Before: 
- After: 
- https://importer-changes--shredit--stericycle.aem.live/en-us

Importer changes wrt to service locations

---

blocks/header/header.css

Fix #161
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/drafts/piyush/en-us
- After: 
- https://nav-changes--shredit--stericycle.aem.live/drafts/piyush/en-us

Country Nav Changes

---

blocks/footer/footer.css
tools/importer/marketing-campaigns.js

Fix 
Test URLs:
- Before: 
- After: 
- https://lint-fix--shredit--stericycle.aem.live/en-us

Lint Error Fix

---

blocks/hero/hero.css

Fix #152
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/service-locations/boston
- After: 
- https://hero-block-changes--shredit--stericycle.aem.live/en-us/service-locations/boston

Hero Block changes

---

blocks/paginated-list/paginated-list.js
styles/styles.css

Fix #205 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/about/news-articles
- https://main--shredit--stericycle.aem.page/en-us/about/press-releases
- After: 
- https://in-the-news--stericycle-shared--aemsites.aem.page/en-us/about/news-articles
- https://in-the-news--stericycle-shared--aemsites.aem.page/en-us/about/press-releases

enable in-the-news

---

blocks/form/form.css
blocks/form/form.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/forms/multistep-inline-regular
- After: 
- https://floating-labels--shredit--stericycle.aem.page/forms/multistep-inline-regular

feat: support for floating labels

---

blocks/form/lib/rules-doc/RuleEngine.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/forms/request-quote
- After: 
- https://fixradio--shredit--stericycle.aem.page/forms/request-quote

fix:visible expression for radio button

---

blocks/form/lib/transform.js
blocks/form/mappings.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/forms/campaign
- After: 
- https://fix-wizard--shredit--stericycle.aem.page/forms/campaign

fix:support wizard type in doc authoring

---

blocks/columns/columns.css
blocks/facet-list/facet-list.js

Fix #223 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/piyush/paper-shredding-services
- After: 
- https://issue-223--shredit--stericycle.aem.page/drafts/piyush/paper-shredding-services

Center Align added for the columns

---

blocks/faq/faq.css
blocks/faq/faq.js

Fix #237 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/new-paper-shredding-services
- After: 
- https://faq-variants--shredit--stericycle.aem.page/en-us/marketing/new-paper-shredding-services

faq variant

---

blocks/form/lib/util.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/forms/campaign
- After: 
- https://error-radio--shredit--stericycle.aem.page/forms/campaign

fix:error message for radio group

---

blocks/form/form.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/forms/multistep-inline
- After: 
- https://fixfont--shredit--stericycle.aem.page/forms/multistep-inline

fix:floating label css getting applied on radio labels

---

blocks/icon-list/icon-list.css

Fix #221 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/residential-shredding-services
- After: 
- https://issue-221--shredit--stericycle.aem.live/en-us/secure-shredding-services/residential-shredding-services

issue-221 icon alignment changes

---

blocks/hero/hero.css
blocks/hero/hero.js
styles/styles.css

Fix #220 
Fix #154 
Fix #152 
Fix #106 
Test URLs:
- https://bug-hero-issues--shredit--stericycle.aem.page/en-us
- https://bug-hero-issues--shredit--stericycle.aem.page/en-us/service-locations
- https://bug-hero-issues--shredit--stericycle.aem.page/en-us/service-locations/boston

Fix numerous issues with hero rendering.

---

styles/styles.css

Fix #222
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://issue-222--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

issue-222 background image changes

---

blocks/offer-box/offer-box.css
blocks/offer-box/offer-box.js

Fix #248 
Regression Test: https://main--stericycle-shared--aemsites.aem.page/en-us/marketing/mobile-shredding-services
Test URLs:
- Before: 
- https://main--stericycle-shared--aemsites.aem.page/en-us/marketing/new-paper-shredding-services
- After: 
- https://offer-box-variant--stericycle-shared--aemsites.aem.page/en-us/marketing/new-paper-shredding-services

add offer-box variant

---

blocks/columns/columns.css

#253 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/invoice-example
- https://www.shredit.com/en-us/marketing/invoice-example
- After: 
- https://columns-labeled--shredit--stericycle.aem.page/en-us/marketing/invoice-example

labeled column variant

---

blocks/columns/columns.css

Fix #254 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/who-we-serve/accountants
- After: 
- https://column-with-border--shredit--stericycle.aem.page/en-us/who-we-serve/accountants

Column with border

---

blocks/form/lib/rules-doc/RuleEngine.js
scripts/delayed.js
scripts/scripts.js
templates/pr-page/pr-page.css
templates/pr-page/pr-page.js

Fix #257 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/about/press-releases/shred-it-identifies-new-threats-emerging-from-the-changing-offic
- https://www.shredit.com/en-us/about/press-releases/shred-it-identifies-new-threats-emerging-from-the-changing-offic
- After: 
- https://related-prs--shredit--stericycle.aem.page/en-us/about/press-releases/shred-it-identifies-new-threats-emerging-from-the-changing-offic

add related content to press release pages

---

blocks/video/video.css

Fix #142 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/myshredit
- After: 
- https://video-js--shredit--stericycle.aem.live/en-us/secure-shredding-services/myshredit

issue-142 redundant changes removed for embed

---

blocks/icon-list/icon-list.css

Fix #216 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/media-destruction-service
- After: 
- https://issue-216--shredit--stericycle.aem.live/en-us/secure-shredding-services/media-destruction-service

issue-216 icon list variant added

---

blocks/flip-cards/flip-cards.css

Fix #215 #153
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/hard-drive-destruction
- After: 
- https://issue-215--shredit--stericycle.aem.live/en-us/secure-shredding-services/hard-drive-destruction

issue-215 padding changed for flip cards

---

blocks/columns/columns.css

Fix #219 #217 #214
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/paper-shredding-services
- After: 
- https://issue-219--shredit--stericycle.aem.live/en-us/secure-shredding-services/paper-shredding-services

issue-219 width changed for columns

---

blocks/facet-list/facet-list.css

Test URLs:
- Before: 
- After: 
- https://<branch>--shredit--stericycle.aem.page/

remove li arrows

---

blocks/footer/footer.css

Fix #163 
Test URLs:
- Before: 
- After: 
- https://issue-163--shredit--stericycle.aem.live/en-us

issue-163 footer design changes

---

styles/styles.css

Fix #145 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/resource-center/info-sheets/common-areas-of-risk-in-the-hospitality-industry
- After: 
- https://issue-145--shredit--stericycle.aem.live/en-us/resource-center/info-sheets/common-areas-of-risk-in-the-hospitality-industry

issue-145 changes in list items

---

scripts/scripts.js

Fix #34 
Test URLs:
- Before: 
- After: 
- https://issue-34--shredit--stericycle.aem.page/en-us

issue-34 aria label added

---

blocks/fragment/fragment.js
blocks/text/text.css
tools/importer/marketing-campaigns.js

Fix #225 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://issue-225--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

Issue-225 fragment changes and text block changes

---

blocks/form/components/radio/radio.js
blocks/form/components/wizard/wizard.css
blocks/form/form.css
blocks/form/lib/util.js

Test URLs:
- Before: 
- After: 
- https://update-style--shredit--stericycle.aem.page/

update style for all forms

---

blocks/form/form.js
blocks/form/utm.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us?utm_source=google&utm_medium=cpc&utm_campaign=spring_sale&utm_term=shoes&utm_content=button
- After: 
- https://utm--shredit--stericycle.aem.page/en-us?utm_source=google&utm_medium=cpc&utm_campaign=spring_sale&utm_term=shoes&utm_content=button

feat:include utm params in form submit data

---

blocks/offer-box/offer-box.css
blocks/offer-box/offer-box.js
scripts/scripts.js
styles/styles.css
templates/marketing-location-page/marketing-location-page.css
templates/marketing-location-page/marketing-location-page.js
templates/service-location-page/service-location-page.css

Fix #273, #272 , #270 , #271 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-paper-shredding-services
- https://main--stericycle-shared--aemsites.aem.page/en-us/service-locations/greenville-spartanburg-asheville - Regression test
- After: 
- https://marketing-fixes--shredit--stericycle.aem.page/en-us/marketing/shred-it-paper-shredding-services
- https://marketing-fixes--stericycle-shared--aemsites.aem.page/en-us/service-locations/greenville-spartanburg-asheville

Marketing fixes

---

styles/styles.css

Fix #49 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/residential-shredding-services
- After: 
- https://issue49--shredit--stericycle.aem.page/en-us/secure-shredding-services/residential-shredding-services

Issue:49 added footer subscription form

---

templates/service-location-page-2/service-location-page-2.js

Fix #28 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/service-locations/huntsville
- After: 
- https://issue28--shredit--stericycle.aem.live/en-us/service-locations/huntsville

added modal form in cards

---

blocks/form/constant.js
blocks/form/lib/forms-common.js

Test URLs:
- Before: 
- After: 
- https://form--shredit--stericycle.aem.page/

feat: Adding google recaptcha

---

blocks/form/lib/forms-common.js

Test URLs:
- Before: 
- After: 
- https://fragment--shredit--stericycle.aem.page/

Supporting Fragment

---

blocks/get-a-quote-form/get-a-quote-form.css
blocks/get-a-quote-form/get-a-quote-form.js

Fix #68 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/tucson
- After: 
- https://inline-form--shredit--stericycle.aem.page/en-us/service-locations/tucson

Added get a quote form inline in service location template.

---

blocks/form/constant.js
blocks/form/submit.js

Test URLs:
- Before: 
- After: 
- https://submit--shredit--stericycle.aem.page/

form: enable submission to dev endpoint

---

blocks/columns/columns.css
blocks/download/download.css
scripts/scripts.js
templates/resource-center/resource-center.css
templates/resource-center/resource-center.js

Fix #144 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/piyush/common-areas-of-risk-in-the-auto-industry
- After: 
- https://download-changes--shredit--stericycle.aem.page/drafts/piyush/common-areas-of-risk-in-the-auto-industry

Download changes

---

blocks/download/download.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/resource-center/infographics/6-tips-to-protect-your-business-from-fraud
- After: 
- https://minor-change--shredit--stericycle.aem.page/en-us/resource-center/infographics/6-tips-to-protect-your-business-from-fraud

Minor changes wrt to underline

---

blocks/columns/columns.css
blocks/columns/columns.js
styles/styles.css

Fix #343, #345 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/who-we-serve/small-business
- After: 
- https://bug-fixes--shredit--stericycle.aem.page/en-us/who-we-serve/small-business

issue-343, issue-345 fixed

---

blocks/offer-box/offer-box.css
blocks/offer-box/offer-box.js

Fix #317 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/marketing/campaign-page-optimized
- After: 
- https://marketing-changes--shredit--stericycle.aem.live/en-us/marketing/campaign-page-optimized

Marketing page offer-box plain changes

---

styles/styles.css

Fix #339 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/who-we-serve/auto
- https://main--shredit--stericycle.aem.live/en-us/who-we-serve/c-suite-executive
- After: 
- https://extra-margin-section--shredit--stericycle.aem.live/en-us/who-we-serve/auto
- https://extra-margin-section--shredit--stericycle.aem.live/en-us/who-we-serve/c-suite-executive

extra margin bottom section introduced

---

blocks/cards/cards.css

Fix #287 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/about/company-overview/leadership
- After: 
- https://leadership-cards--shredit--stericycle.aem.page/en-us/about/company-overview/leadership

enable cards-grid

---

blocks/video/video.js

Fix #334 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/who-we-serve/insurance
- After: 
- https://fix-wistia-color--shredit--stericycle.aem.page/en-us/who-we-serve/insurance

Fix wistia color

---

scripts/aem.js
scripts/scripts.js

Fix 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/tools/sidekick/blocks/offerbox
- After: 
- https://two-column-fix--shredit--stericycle.aem.page/tools/sidekick/blocks/offerbox

Two columns all sections merging removed and undefined block call fixed

---

blocks/offer-box/offer-box.css
blocks/offer-box/offer-box.js

Fix #344 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-document-destruction-and-shredding-prices
- After: 
- https://alternate-2--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

new variant alternate 3 and changes done for alternate 2

---

blocks/offer-box/offer-box.css
templates/templates.js

Fix #333 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/who-we-serve/insurance
- https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-paper-shredding-services
- After: 
- https://sidebar-fix--shredit--stericycle.aem.page/en-us/who-we-serve/insurance
- https://sidebar-fix--shredit--stericycle.aem.page/en-us/marketing/shred-it-paper-shredding-services

Narrow left sidebar fixed

---

scripts/aem.js

Fix #366 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/post-teaser-list&index=0
- After: 
- https://bugfix-366--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/post-teaser-list&index=0

ensure sidekick library can construct appropriate urls

---

blocks/video/video.css

Fix #292 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/professional-shredders-shred-it-and-skateboarding-legend-tony-hawk-team-up
- After: 
- https://vid-rows--shredit--stericycle.aem.page/en-us/professional-shredders-shred-it-and-skateboarding-legend-tony-hawk-team-up

enable flex wrap for recommended videos

---

scripts/scripts.js
templates/marketing-location-page/marketing-location-page.js

Fix 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/locations/paper-shredding-chicago
- After: 
- https://location-marketing-changes--shredit--stericycle.aem.page/en-us/marketing/locations/paper-shredding-chicago

Marketing location changes

---

blocks/columns/columns.css

Fix #370 
Test URLs:
- Before: 
- https://main--stericycle-shared--aemsites.aem.live/en-us/about/company-overview/who-we-are
- After: 
-  https://vid-columns--stericycle-shared--aemsites.aem.live/en-us/about/company-overview/who-we-are

reinstate margin right

---

blocks/quote/quote.css

Fix #311 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding
- After: 
- https://quote-fix--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding

Quote block alternate 1 variant added

---

blocks/tabs/tabs.css
blocks/tabs/tabs.js

Fix #302 
Test URLs:
- Before: 
- https://main--stericycle-shared--aemsites.aem.page/en-us/who-we-serve
- After: 
-  https://topical-tabs--stericycle-shared--aemsites.aem.live/en-us/who-we-serve

topical tabs

---

blocks/form/form.css
scripts/scripts.js
styles/styles.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/blog/100-documents-to-take-to-communtiy-shredding-events
- After: 
- https://footerform--shredit--stericycle.aem.page/en-us/blog/100-documents-to-take-to-communtiy-shredding-events

feat: configure footer-subscription-form via metadata sheet

---

blocks/service-location-map/service-location-map.css
blocks/service-location-map/service-location-map.js
scripts/aem.js
scripts/scripts.js
templates/service-location-page-2/service-location-page-2.css
templates/service-location-page-2/service-location-page-2.js
templates/service-location-page/service-location-page.css
templates/service-location-page/service-location-page.js

Fix #
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/service-locations/cincinnati
- After: 
- https://service-location--shredit--stericycle.aem.live/en-us/service-locations/cincinnati

Service location page template location details fixed

---

blocks/quote/quote.js

Fix #311 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding
- After: 
- https://issue-332--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding

Quote block minor changes

---

templates/service-location-page-2/service-location-page-2.css
templates/service-location-page/service-location-page.css

Fix 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/minneapolis
- After: 
- https://minor-ul-fix--shredit--stericycle.aem.page/en-us/service-locations/minneapolis

minor ul change

---

scripts/scripts.js
templates/service-location-page-2/service-location-page-2.js
templates/service-location-page/service-location-page.css

Fix #157 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/minneapolis
- After: 
- https://minor-loc-fix--shredit--stericycle.aem.page/en-us/service-locations/minneapolis

Minor service locaiton changes

---

scripts/delayed.js
templates/resource-center/resource-center.css
templates/resource-center/resource-center.js

Fix #331
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/resource-center/infographics/boosting-data-compliance-strategy-with-third-party-data-security
- After: 
- https://blog-breadcrump--shredit--stericycle.aem.live/en-us/resource-center/infographics/boosting-data-compliance-strategy-with-third-party-data-security

Breadcrumb added for the resource center apges

---

blocks/form/form.css

Fix #386 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/residential-shredding-services
- After: 
- https://issue386--shredit--stericycle.aem.page/en-us/secure-shredding-services/residential-shredding-services

fix: styling of footer sign up form

---

scripts/scripts.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/residential-shredding-services
- After: 
- https://footer-fix--shredit--stericycle.aem.page/en-us/secure-shredding-services/residential-shredding-services

fix:footer subscription remove url hard-cording

---

blocks/form/constant.js
blocks/form/submit.js

Test URLs:
- Before: 
- After: 
- https://submit--shredit--stericycle.aem.page/

feat: Submit integration

---

blocks/header/nav.js

Fix #160 
Test URLs:
- After: 
- https://bug-service-location-url--shredit--stericycle.aem.page/en-us

Service Location Link Fix

---

blocks/header/alt-2-nav.js
blocks/header/nav.js

Fix #404 
Test URLs:
- After: 
- https://bug-issue-404--shredit--stericycle.aem.page/en-us

Fix Header Quote Links

---

blocks/service-location-map/service-location-map.js

Fix #407 
Test URLs:
- After: 
- https://bug-issue-407--shredit--stericycle.aem.page/en-us

Fix Service Location Form Auto-complete

---

blocks/header/alt-2-nav.css
blocks/header/alt-2-nav.js
templates/marketing-location-page/marketing-location-page.js

Fix #308 
Please note this does not fix the missing anchors, that will be addressed shortly via #405 
Test URLs:
- After: 
- https://bug-issue-308--shredit--stericycle.aem.page/

Fix Missing Header

---

blocks/cards/cards.js
blocks/embed/embed.js
blocks/header/nav.css
blocks/video/video.js
templates/service-location-page-2/service-location-page-2.js
templates/service-location-page/service-location-page.js
tools/importer/infographic.js
tools/importer/resource-center.js

Test URLs:
- After: 
- https://bug-lint--shredit--stericycle.aem.page/en-us

Fix Lint Issues

---

blocks/header/nav.css

Fix #162 
Test URLs:
- After: 
- https://bug-search-hover--shredit--stericycle.aem.page/en-us

Fix Search Hover State

---

blocks/get-a-quote-form/get-a-quote-form.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/tucson
- After: 
- https://locations-form--shredit--stericycle.aem.page/en-us/service-locations/tucson

fix:locations form

---

blocks/quote/quote.css
scripts/scripts.js

Fix #311 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding
- After: 
- https://test-changes--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding

testimonial changes

---

scripts/aem.js
scripts/scripts.js
templates/marketing-location-page/marketing-location-page.js
templates/resource-center/resource-center.js
templates/service-location-page/service-location-page.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/marketing/locations/paper-shredding-wichita
- https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding
- https://main--shredit--stericycle.aem.live/en-us/service-locations/cincinnati
- https://main--shredit--stericycle.aem.live/en-us/resource-center/info-sheets/common-areas-of-risk-in-the-auto-industry
- After: 
- https://cls-issue-fix--shredit--stericycle.aem.live/en-us/marketing/locations/paper-shredding-wichita
- https://cls-issue-fix--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding
- …

CLS issues fixes

---

blocks/faq/faq.css

Fix #419 
Test URLs:
- After: 
- https://bug-issue-419--shredit--stericycle.aem.page/en-us/resource-center/faq

Fix FAQ styling.

---

blocks/post-teaser-list/post-teaser-list.js

Fix #418 
Test URLs:
- After: 
- https://bug-issue-418--shredit--stericycle.aem.page/en-us/secure-shredding-services/hard-drive-destruction

Fix Issue 418 - Add Link to categories

---

blocks/clickable-columns/clickable-columns.css

Fix #417 
Test URLs:
- After: 
- https://bug-issue-417--shredit--stericycle.aem.page/en-us

Issue 417 - Consistent content alignment

---

blocks/clickable-columns/clickable-columns.js

Fix #416 
Links should be processed by the AEM server to be relative to current context. 
Use URL constructor to validate URL.
Test URLs:
- After: 
- https://bug-issue-416--shredit--stericycle.aem.page/en-us

Fix 416 - Fix Links

---

styles/styles.css

Fix #414 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/cards&index=6
- After: 
- https://fix-checkmarks--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/cards&index=6

fix checkmark alignment

---

blocks/banner/banner.css
blocks/banner/banner.js

Resolve #377
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/janlucaa/banner/page-with-banner
- After: 
- https://issue-377--shredit--stericycle.aem.page/drafts/janlucaa/banner/page-with-banner

Add banner block

---

blocks/form/constant.js

Test URLs:
- Before: 
- After: 
- https://submit-stage--shredit--stericycle.aem.page/

form submit to stage endpoint

---

blocks/columns/columns.css
blocks/columns/columns.js
blocks/hero/hero.css
blocks/video/video.css
styles/styles.css

Fix #310 
Fix #338 
Fix #401 
Fix #402 
Fix #413 
Test URLs:
- After: 
- https://bug-styling-issues--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding
- https://bug-styling-issues--shredit--stericycle.aem.page/en-us/who-we-serve/finance
- https://bug-styling-issues--shredit--stericycle.aem.page/en-us
- https://bug-styling-issues--shredit--stericycle.aem.page/en-us/who-we-serve/auto

Various Styling Bug Fixes

---

blocks/simple-cta/simple-cta.css
blocks/simple-cta/simple-cta.js
templates/service-location-page/service-location-page.js

Fix #400
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/birmingham-usa
- https://main--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
- https://main--shredit--stericycle.aem.page/tools/sidekick/blocks/simple-cta
- After: 
- https://issue-400--shredit--stericycle.aem.page/
- https://issue-400--shredit--stericycle.aem.page/en-us/service-locations/birmingham-usa
- https://issue-400--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
- https://issue-400--shredit--stericycle.aem.page/tools/sidekick/blocks/simple-cta

Refactor simple CTA block

---

blocks/form/form.css
styles/styles.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/email/tiered-shredding
- After: 
- https://pop-up--shredit--stericycle.aem.page/en-us/email/tiered-shredding

feat:created get a quote pop block

---

blocks/blog-cards/blog-cards.css
blocks/blog-filter/blog-filter.css
blocks/clickable-columns/clickable-columns.css
blocks/columns/columns.css
blocks/facet-list/facet-list.css
blocks/faq/faq.css
blocks/featuretable/featuretable.css
blocks/flip-cards/flip-cards.css
blocks/footer/footer.css
blocks/form/components/radio/radio.css
blocks/form/components/wizard/wizard.css
blocks/form/form.css
blocks/header/alt-0-nav.css
blocks/header/alt-1-nav.css
blocks/header/alt-2-nav.css
blocks/header/nav.css
blocks/offer-box/offer-box.css
blocks/service-location-map/service-location-map.css
blocks/tabs/tabs.css
blocks/testimonial/testimonial.css
plugins/experimentation/src/preview.css
styles/styles.css

**Ticket**
https://herodigital.atlassian.net/browse/STERI016-50
Fix #STERI016-50
**Changes:**
- Updated hardcoded colors to use proper CSS variables.
**Test URLs:**
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/
- After: 
- https://feat-steri016-50-ch--shredit--stericycle.aem.page/

STERI-016-50: Update color tokens

---

blocks/header/nav.css
blocks/header/nav.js
scripts/scripts.js
templates/service-location-page/service-location-page.js

Fix #444 
Test URLs:
- After: 
- https://feat-fixed-contact-footer--shredit--stericycle.aem.page/en-us

Fix 444 - Add Sticky CTA Buttons

---

blocks/columns/columns.css
blocks/hero/hero.css
blocks/paginated-list/paginated-list.css
blocks/testimonial/testimonial.css
styles/styles.css

Fix #402 
Fix #443 
Fix #456 
Fix #459 
Test URLs:
- After: 
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us/test
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us/about/media-contacts
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us/about/social-responsibility/diversity-inclusion
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us/about/news-articles
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us/about/press-releases
- https://bug-more-style-issues--shredit--stericycle.aem.page/en-us/who-we-serve/finance

Various Styling Fixes

---

blocks/flip-cards/flip-cards.css

Fix #494
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services
- After: 
- https://issue-494--shredit--stericycle.aem.page/en-us/secure-shredding-services

Restrict card flipping to tablet size and up

---

blocks/hero/hero.css

Fix #469
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/about/press-releases
- After: 
- https://issue-469--shredit--stericycle.aem.page/en-us/about/press-releases

Minor fixes to hero styling

---

blocks/flip-cards/flip-cards.js

Fix #467 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/piyush/about
- After: 
- https://flip-card-change--shredit--stericycle.aem.page/drafts/piyush/about

Flip card changes

---

blocks/columns/columns.css
blocks/flip-cards/flip-cards.css

Fix #493
(Not a huge fan of the column styles we currently use, but I also didn't feel like refactoring all of it, so I just went with it and fixed the issue)
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/fragments/why-choose-shredit
- After: 
- https://issue-493--shredit--stericycle.aem.page/en-us/fragments/why-choose-shredit

Fix icons in fragment

---

blocks/clickable-columns/clickable-columns.css
blocks/footer/footer.css
blocks/form/form.css
blocks/header/nav.css
blocks/post-teaser-list/post-teaser-list.js
styles/styles.css

**Ticket**
https://herodigital.atlassian.net/browse/STERI016-57
Fix #STERI016-50
**Changes:**
- Updated buttons styling with design system rules
**Demo URL:**
https://feat-steri016-57--shredit--stericycle.aem.page/drafts/conary/document
**Test URLs:**
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/
- After: 
- https://feat-steri016-57--shredit--stericycle.aem.live/

STERI-016-57: Update buttons styling

---

blocks/columns/columns.css

Fix #466 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://narrow-icon-change--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

Narrow icon changes

---

blocks/columns/columns.css
blocks/faq/faq.css
blocks/form/form.css
blocks/hero/hero.css
blocks/icon-list/icon-list.css
blocks/offer-box/offer-box.css
styles/styles.css

Fix #504 #333 #490 #496 #491 #488 #487 #485 #484 #474 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding
- https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/specialty-shredding-service
- After: 
- https://small-fixes--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding
- https://small-fixes--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service
- https://small-fixes--shredit--stericycle.aem.live/en-us/secure-shredding-ser …

Small fixes

---

blocks/form/form.css
styles/styles.css

**Ticket**
https://herodigital.atlassian.net/browse/STERI016-58
**Changes:**
- Updated InputFIeld styling with design system rules
**Demo URL:**
https://feat-steri0-16-58-ch--shredit--stericycle.aem.page/en-us/offer
**Test URLs:**
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/
- After: 
- https://feat-steri0-16-58-ch--shredit--stericycle.aem.live/

STERI016-58: Update input field color tokens

---

blocks/breadcrumb/breadcrumb.css
blocks/breadcrumb/breadcrumb.js
blocks/download/download.css
blocks/download/download.js
blocks/footer/footer.js
blocks/fragment/fragment.js
blocks/header/nav.css
blocks/related-content/related-content.css
blocks/related-content/related-content.js
scripts/delayed.js
scripts/scripts.js
styles/styles.css
templates/resource-center/resource-center.css
templates/resource-center/resource-center.js

Created a new approach to handling sidebar pages - this effectively uses a dummy block to indicate where the content should split between left & right.
* Sidebar Right -> 75/25 column split
* Sidebar Left - 25/75 Column split (CSS not defined yet but easy to add)
Fix #141 
Test URLs:
- After: 
- https://bug-resource-center-template--shredit--stericycle.aem.page/en-us/resource-center/videos/data-breaches-understanding-todays-threats
- https://bug-resource-center-template--shredit--stericycle.aem.page/en-us/resource-center/infographics/6-tips-to-protect-your-business-from-fraud

Resource Center Template Refactor

---

scripts/scripts.js

Fix #363
Test URLs:
- Before: 
- After: 
- https://issue-363--shredit--stericycle.aem.page/

Fix json-ld

---

blocks/modal/modal.css

Fix #448 
Test URLs:
- Before: 
- After: 
- https://issue448--shredit--stericycle.aem.page/

fix: modal mobile rendering issues

---

scripts/scripts.js

Fix #521 
Test URLs:
- After: 
- https://bug-issue-521--shredit--stericycle.aem.page/en-us

Hero Auto Block Fix

---

blocks/form/form.css

Fix #486 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/offer
- After: 
- https://issue486--shredit--stericycle.aem.page/en-us/offer

Issue486: fix forms mobile layout

---

blocks/form/form.css
styles/styles.css

**Ticket**
https://herodigital.atlassian.net/browse/STERI016-59
**Changes:**
- Updated `Radio` and `Checkbox` styling with design system rules
**Demo URL:**
https://feat-steri016-59-ch--shredit--stericycle.aem.page/en-us/offer
**Test URLs:**
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/
- After: 
- https://feat-steri016-59-ch--shredit--stericycle.aem.live/

STERI016-59 Radio button style update

---

blocks/video/video.css
blocks/video/video.js

Fix #523 
Test URLs:
- After: 
- https://bug-issue-523--shredit--stericycle.aem.page/en-us/resource-center/videos/data-breaches-understanding-todays-threats

Lazy load video observer.

---

blocks/columns/columns.css
styles/styles.css

Fix #488
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/janlucaa/list-styles
- After: 
- https://issue-488--shredit--stericycle.aem.page/drafts/janlucaa/list-styles

Minor fix to the big number list style

---

blocks/tabs/tabs.css
blocks/tabs/tabs.js

Fix #510
Test URLs:
- After: 
- https://bug-issue-510--shredit--stericycle.aem.page/en-us/who-we-serve#tab-by-role-responsibility

Support window hash state for tabs.

---

scripts/scripts.js

Fix #363
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/janlucaa/schema-test
- After: 
- https://issue-363--shredit--stericycle.aem.page/drafts/janlucaa/schema-test

Fix json-ld & improve security

---

blocks/faq/faq.css
blocks/faq/faq.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-49
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://steri016-49-faq-block--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

STERI016-101: Faq block styles updated

---

blocks/columns/columns.css
blocks/columns/columns.js
blocks/tabs/tabs.css
blocks/video/video.css

Fix #531 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/professional-shredders-shred-it-and-skateboarding-legend-tony-hawk-team-up
- After: 
- https://vid-aspect--shredit--stericycle.aem.page/en-us/professional-shredders-shred-it-and-skateboarding-legend-tony-hawk-team-up

fix video aspect ratio

---

blocks/service-location-map/service-location-map.css
blocks/service-location-map/service-location-map.js

Fix #489 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/service-locations
- After: 
- https://issue-489--shredit--stericycle.aem.live/en-us/service-locations

issue-489 Service location map changes

---

blocks/hero/hero.css
blocks/hero/hero.js
scripts/scripts.js

Fix #527 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/drafts/piyush/en-us
- After: 
- https://hero-block-changes--shredit--stericycle.aem.live/drafts/piyush/en-us
- https://hero-block-changes--shredit--stericycle.aem.live/en-us

Hero Block changes wrt to desktop and mobile images

---

blocks/search/search.css
blocks/search/search.js

Fix #450 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/search?searchQuery=video
- After: 
- https://fix-search--shredit--stericycle.aem.page/en-us/search?searchQuery=video

fix search

---

blocks/offer-box/offer-box.css

Fix #319
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
- After: 
- https://issue-319--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

issue-319 spacing fixed

---

scripts/aem.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-112
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/buttons-with-icons
- After: 
- https://steri016-112-button-with-icons-am--shredit--stericycle.aem.live/refresh-testing/buttons-with-icons

STERI016-112-button-with-icons-am: Button with icons

---

styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-63
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/tools/sidekick/blocks/sections
- After: 
- https://steri016-63-bullets-am--shredit--stericycle.aem.live/tools/sidekick/blocks/sections

STERI016-63-bullets-am: Add Bullet Style

---

blocks/form/components/mask/mask.css
blocks/form/components/mask/mask.js
blocks/form/form.css
blocks/modal/modal.css

Fix #544 
Fix #516 
Fix #514 
Fix #386 
Fix #358 
Fix #547
Fix #555
Fix #547
Fix #460 
Fix #496 
Test URLs:
- Before: 
- After: 
- https://get-a-quote--shredit--stericycle.aem.page/

fixed multiple form css issues

---

styles/styles.css

Fix #556 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline
- After: 
- https://issue-556--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline

issue-556 scrolling smooth

---

blocks/form/form.js
templates/marketing-location-page/marketing-location-page.js
templates/service-location-page/service-location-page.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/tucson
-  https://main--shredit--stericycle.aem.page/en-us/marketing/locations/paper-shredding-columbus
- After: 
- https://locations--shredit--stericycle.aem.page/en-us/service-locations/tucson
-  https://locations--shredit--stericycle.aem.page/en-us/marketing/locations/paper-shredding-columbus

fix:allow author to configure form in locations pages

---

blocks/faq/faq.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-163
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/one-off-shredding-service
- After: 
- https://steri016-163-faq-mobile-issue-am--shredit--stericycle.aem.live/refresh-testing/one-off-shredding-service

STERI016-163-faq-mobile-issue-am: Remove hover styles on mobile

---

blocks/footer/footer.js
blocks/header/alt-2-nav.js
blocks/header/nav.js

Fix #557 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
- After: 
- https://issue557--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
- https://issue557--shredit--stericycle.aem.page/en-us

fix: make nav and footer modal configurable

---

templates/service-location-page/service-location-page.js

Fix #578
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/service-locations/kansas-city
- After: 
- https://flip-change--shredit--stericycle.aem.live/en-us/service-locations/kansas-city

Flip changes

---

blocks/footer/footer.js

Fix #557 
Test URLs:
- Before: 
- After: 
- https://fix-footer--shredit--stericycle.aem.page/

fix: footer modal button not rendering

---

blocks/quote/quote.css
blocks/quote/quote.js
styles/styles.css

Fix https://herodigital.atlassian.net/browse/STERI016-104
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/quote
After:
https://steri016-104-ch--shredit--stericycle.aem.live/drafts/conary/quote

Steri016 104 ch

---

blocks/hero/hero.css
blocks/hero/hero.js
styles/styles.css

Fix #156 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/boston
- After: 
- https://issue156--shredit--stericycle.aem.page/en-us/service-locations/boston

fix:add request a quote button inside header for mobile view

---

scripts/scripts.js

Part of #365
Test URLs:
- Before: 
- After: 
- https://fix-launch-urls--shredit--stericycle.aem.page/

Fix launch urls

---

blocks/hero-banner/hero-banner.css
styles/styles.css

Fix https://herodigital.atlassian.net/browse/STERI016-82
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/hero
After:
https://hero-image-ch--shredit--stericycle.aem.live/drafts/conary/hero

Hero image ch

---

styles/styles.css

Fix:  no ref
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/hero
After:
https://page-width-ch--shredit--stericycle.aem.live/drafts/conary/hero

no-ref: Revert page width update

---

scripts/scripts.js

Part of #365 
Test URLs:
- Before: 
- After: 
- https://change-launch-environment--shredit--stericycle.aem.page/

Change launch environment

---

blocks/hero-banner/hero-banner.css
styles/styles.css

Fix: no-ref
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/hero
After:
https://full-wdith-content-ch--shredit--stericycle.aem.live/drafts/conary/hero

no-ref: Add new xxl container token

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-195
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/forms/landing-page-hardrive
- After: 
- https://steri016-195-input-field-am--shredit--stericycle.aem.live/forms/landing-page-hardrive

STERI016-195-input-field-am: Fix inconsistencies in font sizes

---

blocks/faq/faq.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-147
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/refresh-testing/one-off-shredding-service
- After: 
- https://steri016-147-faq-issue-am--shredit--stericycle.aem.live/refresh-testing/one-off-shredding-service

STERI016-147-faq-issue-am: Add margin between sections when options are opened with focus

---

styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-172
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/buttons
- After: 
- https://steri016-172-buttons-visual-am--shredit--stericycle.aem.page/refresh-testing/buttons

STERI016-172-buttons-visual-am: Fix Hover Behavior and Icon Arrow Issues

---

blocks/flip-cards/flip-cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-191
Test URLs:
- Before: 
- After: 
- https://steri016-191-restrict-cards-am--shredit--stericycle.aem.live/refresh-testing/flip-cards

STERI016-191-restrict-cards-am: Restrict Flip-Cards to Maximum Four Cards

---

scripts/delayed.js
scripts/martech.js
scripts/scripts.js

Part of #365 
Test URLs:
- Before: 
- After: 
- https://martech-changes--shredit--stericycle.aem.page/en-us

Enable Google Tag manager

---

blocks/form/form.css
blocks/modal/modal.css

Fix #574 
Fix #571
Fix #460 
Fix #547 
Fix #505 
Fix #561 
Test URLs:
- Before: 
- After: 
- https://form-fixes--shredit--stericycle.aem.page/

fix: form styling issues

---

scripts/delayed.js
scripts/martech.js

Resolve #606
Test URLs:
- Before: 
- After: 
- https://issue-606--shredit--stericycle.aem.page/

Add cookie banner

---

blocks/header/alt-2-nav.js

Fix #556 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline
- After: 
- https://alt-nav-2--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline

Alt Nav changes for the service header links

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-194
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/forms/landing-page-hardrive
- After: 
- https://steri016-194-input-issues-am--shredit--stericycle.aem.live/forms/landing-page-hardrive

STERI016-194-input-issues-am: Input Field - Visual inconsistencies (Color)

---

blocks/cards/cards.css
blocks/cards/cards.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-129
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/refresh-testing/cards
- After: 
- https://steri016-129-cards-block-am--shredit--stericycle.aem.live/refresh-testing/cards

STERI016-129-cards-block-am: Enhance Full-Width Styles for Cards Block

---

blocks/offer-box/offer-box.css

Fix #344 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices
- After: 
- https://temp-fix--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

Fix for icons

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-194
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/forms/landing-page-hardrive
- After: 
- https://steri016-194-input-color-issues-am--shredit--stericycle.aem.live/forms/landing-page-hardrive

STERI016-194-input-color-issues-am: Input Field - Visual inconsistencies (Changes)

---

blocks/header/nav.css

Fix #632 
Test URLs:
- Before: 
- After: 
- https://issue-648--shredit--stericycle.aem.live/en-us

issue-632 Icon changes

---

blocks/simple-cta/simple-cta.css

Fix #642 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
- After: 
- https://issue-642--shredit--stericycle.aem.live/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus

issue-642 Button changes

---

blocks/footer/footer.css

Fix #634 
Test URLs:
- Before: 
- After: 
- https://issue-634--shredit--stericycle.aem.live/en-us

issue-634 Footer changes

---

blocks/icon-list/icon-list.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-127
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/icon-list
- After: 
- https://steri016-127-icon-list-am--shredit--stericycle.aem.live/refresh-testing/icon-list

STERI016-127-icon-list-am: Icon List Block (Icon List with Split First Third)

---

blocks/form/constant.js

Test URLs:
- Before: 
- After: 
- https://submit-url--shredit--stericycle.aem.page/

make submit url relative for stage and prod

---

scripts/martech.js

Resolve #629
Test URLs:
- Before: 
- After: 
- https://issue-629--shredit--stericycle.aem.page/

Push page properties to dataLayer

---

blocks/cards/cards.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-47
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/refresh-testing/cards
- After: 
- https://steri016-47-cards-primary-am--shredit--stericycle.aem.live/refresh-testing/cards

STERI016-47: Cards block - Primary Cards

---

blocks/icon-list/icon-list.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-128
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/sections-features
- After: 
- https://steri016-128-section-am--shredit--stericycle.aem.live/refresh-testing/sections-features

STERI016-128: Section Block

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-59
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/forms/campaign-regular
- After: 
- https://steri016-59-radio-button-am--shredit--stericycle.aem.live/forms/campaign-regular

STERI016-59-radio-button-am: Radio Button

---

styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-245
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/hero
- After: 
- https://steri016-245-hero-button-focus-am--shredit--stericycle.aem.live/refresh-testing/hero

STERI016-245-hero-button-focus-am: Hero - Primary Button

---

blocks/form/components/wizard/wizard.css
blocks/form/components/wizard/wizard.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-143
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/forms/campaign
- After: 
- https://steri016-143-stepper-am--shredit--stericycle.aem.live/forms/campaign

STERI016-143-stepper-am: Atom - Stepper

---

blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-247
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/hero
- After: 
- https://steri016-247-hero-mobile-width-am--shredit--stericycle.aem.live/refresh-testing/hero

STERI016-247: Hero Image

---

blocks/form/integrations/recaptcha.js

Test URLs:
- Before: 
- After: 
- https://recaptcha--shredit--stericycle.aem.page/

fix: form without submit button not rendering if captcha is configured

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-236
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/forms/landing-page-hardrive
- After: 
- https://steri016-236-checkbox-mobile-am--shredit--stericycle.aem.live/forms/landing-page-hardrive

STERI016-236 Fix checkbox styling issue on mobile when unchecked

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-220
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/forms/landing-page-hardrive
- After: 
- https://steri016-223-input-am--shredit--stericycle.aem.live/forms/landing-page-hardrive

STERI016-220: Input fields & Buttons are not rendering on Mobile view

---

blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-246
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/hero
- After: 
- https://steri016-246-hero-tablet-am--shredit--stericycle.aem.live/refresh-testing/hero

STERI016-246: Adjust hero image layout for tablet screens

---

blocks/tabs/default.css

Fix https://herodigital.atlassian.net/browse/STERI016-250
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/tabs
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/tabs-vertical
After:
https://bug-fix-steri016-250-ch--shredit--stericycle.aem.live/drafts/conary/tabs
https://bug-fix-steri016-250-ch--shredit--stericycle.aem.live/drafts/conary/tabs-vertical

STERI016-250: Add gap and flex property to tabs panel div

---

styles/styles.css

Fix #640 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/email/pricing
- After: 
- https://quote-issue--shredit--stericycle.aem.live/en-us/email/pricing

issue-640 Spacing issues fixed

---

blocks/hero/hero.js

Fix #211 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/drafts/piyush/en-us
- After: 
- https://issue-211--shredit--stericycle.aem.live/drafts/piyush/en-us

issue-211 Image quality improved for the hero block

---

blocks/cards/cards.css
blocks/columns/default.css
blocks/columns/default.js
blocks/offer-box/offer-box.css
styles/styles.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/national-accounts/una
- After: 
- https://fix-una--shredit--stericycle.aem.live/en-us/national-accounts/una

add xxxl icon

---

styles/styles.css

Fix #633
Test URLs:
- Before: 
- After: 
- https://issue-633--shredit--stericycle.aem.page/

Add cookie button style override

---

blocks/columns/default.css

Fix #466 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://issue-466--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

issue-466 Narrow icons fix

---

blocks/flip-cards/flip-cards.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-271
Test URLs:
- Before: 
- After: 
- https://steri016-271-flip-cards-block-am--shredit--stericycle.aem.live/refresh-testing/flip-cards

STERI016-271: Flip-cards block - Inconsistencies in font sizes

---

blocks/quote/quote.css
blocks/quote/quote.js
styles/styles.css

Fix https://herodigital.atlassian.net/browse/STERI016-233
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/quote
After:
https://steri016-233-ch--shredit--stericycle.aem.live/drafts/conary/quote

STERI016-233: Update quote block styles and add title support

---

blocks/header/nav.js
blocks/header/utils.js
scripts/scripts.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-298
Test URLs:
Before:
After:
https://steri016-298-ch--shredit--stericycle.aem.live/en-us

STERI016-298: Add layout change support

---

styles/styles.css

Fix #496 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/blog/proactive-data-protection-safeguarding-consumer-trust-and-reducing-breach-risks
- After: 
- https://blog-margins--shredit--stericycle.aem.page/en-us/blog/proactive-data-protection-safeguarding-consumer-trust-and-reducing-breach-risks

fix blog margins

---

blocks/columns/default.css
blocks/header/alt-2-nav.css
styles/styles.css

Fix #315 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/hard-drive-destruction-service
- https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
- After: 
- https://nav-2-margins--shredit--stericycle.aem.page/en-us/marketing/hard-drive-destruction-service
- https://nav-2-margins--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

sem margin fixes

---

blocks/form/form.css
blocks/offer-box/offer-box.css
templates/marketing-location-page/marketing-location-page.css
templates/marketing-location-page/marketing-location-page.js

Fix #564 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/document-destruction-for-one-time-and-regular
- After: 
- https://mobile-sem--shredit--stericycle.aem.page/en-us/marketing/document-destruction-for-one-time-and-regular

fixes sem page mobile view

---

blocks/footer/footer.js
blocks/post-teaser-list/post-teaser-list.js
scripts/martech.js
scripts/scripts.js

Part of #688
Test URLs:
- Before: 
- After: 
- https://issue-688--shredit--stericycle.aem.page/

WIP: add CTA events

---

blocks/columns/default.css

Fix #701 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/national-accounts/una
- After: 
- https://spacing-fixes--shredit--stericycle.aem.page/en-us/national-accounts/una

fix una spacing

---

blocks/banner/banner.css
blocks/banner/banner.js
blocks/flip-cards/flip-cards.js
blocks/header/nav.css
scripts/scripts.js
styles/styles.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/mrosier/document
- After: 
- https://move-banner--shredit--stericycle.aem.page/drafts/mrosier/document

make banner work through metadata

---

blocks/banner/banner.js

Resolve #689
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/mrosier/document
- After: 
- https://issue-689--shredit--stericycle.aem.page/drafts/mrosier/document

Add topbar analytics triggers

---

blocks/flip-cards/flip-cards.js

Fix #224 
Test URLs:
- Before: 
- https://main--stericycle-shared--aemsites.aem.page/en-us/secure-shredding-services/residential-shredding-services
- After: 
- https://teaser-text--stericycle-shared--aemsites.aem.page/en-us/secure-shredding-services/residential-shredding-services

Teaser text

---

styles/styles.css

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/sitemap
- After: 
- https://sitemap-add--shredit--stericycle.aem.page/en-us/sitemap

style sitemap

---

blocks/footer/constants.js
blocks/footer/footer.css
blocks/footer/footer.js
blocks/footer/utils.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-87
Test URLs:
- Before: 
- After: 
- https://steri016-87-footer-am--shredit--stericycle.aem.live/en-us

STERI016-87: Footer block

---

templates/service-location-page-2/service-location-page-2.js

Fix 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/erie
- After: 
- https://cls-change--shredit--stericycle.aem.page/en-us/service-locations/erie

CLS fix for the service location page 2 template

---

scripts/scripts.js

Fix #717
Test URLs:
- Before: 
- After: 
- https://issue-717--shredit--stericycle.aem.page/

Fix invoca race-condition

---

blocks/cards/cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-278
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/cards
- After: 
- https://steri016-278-cards-block-am--shredit--stericycle.aem.live/refresh-testing/cards

STERI016-278: Cards block Issue

---

blocks/flip-cards/flip-cards.css
blocks/flip-cards/flip-cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-177
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/allan/flip-cards
After:
https://steri016-177-ch--shredit--stericycle.aem.live/drafts/allan/flip-cards

STERI016-177: Add eyebrow styling to flip cards

---

scripts/scripts.js
templates/service-location-page/service-location-page.js

Fix 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/service-locations/cincinnati
- After: 
- https://cls-issue--shredit--stericycle.aem.live/en-us/service-locations/cincinnati

CLS fix on service location pages

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-299
Test URLs:
Before:
After:
https://steri016-299-ch--shredit--stericycle.aem.live/en-us

Steri016 299 ch

---

blocks/blog-filter/blog-filter.js
blocks/breadcrumb/breadcrumb.js
blocks/facet-list/facet-list.js
blocks/paginated-list/paginated-list.js
blocks/service-location-list/service-location-list.js
blocks/service-location-map/service-location-map.js
scripts/scripts.js

This is high priority to get out of the current limbo state with our query-indices.
I tried to manually check and test at least one page per affected code change. However, please confirm yourself if I missed something that's broken because of this.
Resolve #724
Test URLs:
- Before: 
- After: 
- https://issue-724--shredit--stericycle.aem.page/

Switch to localized query-index

---

blocks/flip-cards/flip-cards.js
blocks/search/search.js

Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/search
- After: 
- https://fix-wrong-index--shredit--stericycle.aem.page/en-us
- https://fix-wrong-index--shredit--stericycle.aem.page/en-us/search

Hotfix: Update references manually fetching the query-index

---

blocks/banner/banner.js
blocks/columns/default.css
blocks/faq/faq.css
blocks/search/search.js
blocks/text/text.css
styles/styles.css

Fix #729 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/search?searchQuery=milwaukee
- After: 
- https://search-regression-fix--shredit--stericycle.aem.page/en-us/search?searchQuery=milwaukee

fixes search

---

blocks/icon-list/icon-list.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-127
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/icon-list
- After: 
- https://steri016-127-icon-numbers-am--shredit--stericycle.aem.live/refresh-testing/icon-list

STERI016-127: Icon List Block(Mobile number styles)

---

blocks/icon-list/icon-list.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-327
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/sections-features
- After: 
- https://steri016-327-section-am--shredit--stericycle.aem.live/refresh-testing/sections-features

STERI016-327: Section Block - UAT issues

---

blocks/columns/default.css
blocks/footer/footer.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-48
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/columns-features
- After: 
- https://steri016-48-columns-am--shredit--stericycle.aem.live/refresh-testing/columns-features

STERI016-48: Columns Block

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-310
Test URLs:
Before:
After:
https://steri016-310-ch--shredit--stericycle.aem.live/en-us

Steri016 310 Header - [Get in touch] Inconsistencies in font size and color

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-301
Test URLs:
Before:
After:
https://steri016-301-ch--shredit--stericycle.aem.live/en-us

STERI016-301: Add margin and max-width to search form in header nav

---

blocks/columns/default.css
blocks/columns/default.js
blocks/faq/faq.css

Fix #729 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
- After: 
- https://faq-style--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus

extend styling gray background

---

blocks/form/constant.js

Fix #732 
Test URLs:
- Before: 
- After: 
- https://email--shredit--stericycle.aem.page/

fix: email regex validation

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-306
Test URLs:
Before:
After:
https://steri016-306-ch--shredit--stericycle.aem.live/en-us

STERI016-306: Refactor contact modal title style in header

---

blocks/form/lib/forms-common.js

Fix #745 
Test URLs:
- Before: 
- After: 
- https://issue745--shredit--stericycle.aem.page/

fix: exclude hidden fields from validation during submission

---

blocks/modal/modal.js

Fix #723 
Test URLs:
- Before: 
- After: 
- https://issue723--shredit--stericycle.aem.page/

fix: added a buffer zone around modal so that accidental user clicks don't close modal

---

styles/styles.css

Fix: https://herodigital.atlassian.net/browse/STERI016-295
Test URLs:
- Before: 
- After: 
- https://steri016-295-button-am--shredit--stericycle.aem.live/refresh-testing/flip-cards

STERI016-295: Button - Primary Button issue

---

blocks/flip-cards/flip-cards.js

Ticket: No ref
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/flip-cards
After:
https://no-ref-flip-cards-ch--shredit--stericycle.aem.live/refresh-testing/flip-cards

fix: Fix eyebrow link check in flip-cards.js

---

blocks/cards/cards.css
blocks/cards/cards.js

Fix: https://herodigital.atlassian.net/browse/STERI016-296
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/cards
- After: 
- https://steri016-296-card-am--shredit--stericycle.aem.live/refresh-testing/cards

STERI016-296: Card Block - Primary Card CTA Issues

---

blocks/tabs/default.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-339
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/tabs
- After: 
- https://steri016-339-tabs-am--shredit--stericycle.aem.live/refresh-testing/tabs
Note: Since there was no defined image style, I applied a max-width of 500px to prevent the image from occupying excessive width.

STERI016-339: Tabs Block - UAT issue

---

blocks/cards/cards.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-305
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/cards
- After: 
- https://steri016-305-card-am--shredit--stericycle.aem.live/refresh-testing/cards

STERI016-305: Fix mobile alignment and stroke visibility issues.

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-304
Test URLs:
Before:
After:
https://steri016-304-ch--shredit--stericycle.aem.live/en-us

STERI016-304: Refactor header padding and remove unnecessary media query

---

blocks/facet-list/facet-list.js

Fix #764 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/resource-center
- After: 
- https://facet-changes--shredit--stericycle.aem.page/en-us/resource-center

Facet list changes wrt to filtering

---

blocks/offer-box/offer-box.css
blocks/offer-box/offer-box.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-85
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/tools/sidekick/blocks/offerbox
After:
https://steri016-85-ch--shredit--stericycle.aem.live/tools/sidekick/blocks/offerbox

STERI016-85: Refactor OfferBox component with new styling

---

blocks/form/lib/forms-common.js
blocks/form/lib/transform.js
blocks/form/submit.js

Fix #769 
Test URLs:
- Before: 
- After: 
- https://issue769--shredit--stericycle.aem.page/

fix:default values for single checkboxes

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-304
Test URLs:
Before:
After:
https://steri016-304-nav-ch--shredit--stericycle.aem.live/en-us

STERI016-304: Add letter-spacing and text-decoration to header nav

---

blocks/columns/default.css
blocks/columns/default.js
blocks/form/form.css
blocks/offer-box/offer-box.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-176
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/getquote
After:
https://steri016-176-ch--shredit--stericycle.aem.live/drafts/conary/getquote

STERI016-176: Update CSS styles for columns, form, and offer-box

---

blocks/footer/footer.css
blocks/footer/footer.js
blocks/footer/utils.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-366
Test URLs:
- Before: 
- After: 
- https://steri016-366-footer-am--shredit--stericycle.aem.live/en-us

STERI016-366: Footer - Unable to click on link titles

---

blocks/faq/faq.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-300
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://steri016-300-faq-am--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

STERI016-300: FAQ - Visual inconsistencies in FAQ

---

blocks/form/components/mask/mask.css
blocks/form/form.css
blocks/get-a-quote-form/get-a-quote-form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-387
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/sections-features
After:
https://steri016-387-ch--shredit--stericycle.aem.live/refresh-testing/sections-features

STERI016-387: Update alternate form CSS styles

---

blocks/footer/footer.css
blocks/footer/footer.js
blocks/footer/utils.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-321
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/hero-autoblocking
- After: 
- https://steri016-321-footer-am--shredit--stericycle.aem.live/refresh-testing/hero-autoblocking

STERI016-321-footer-am: Add Footer short version

---

blocks/columns/default.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-390
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/columns-features
- After: 
- https://steri016-390-columns-am--shredit--stericycle.aem.live/refresh-testing/columns-features
Note: This applies to the last column example, specifically in the mobile view, previously it did not place the left and right padding correctly.

STERI016-390: Columns - Padding is removed when another column is added to a section

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-299
Test URLs:
Before:
After:
https://steri016-299-font-style-ch--shredit--stericycle.aem.live/en-us

STERI016-299: Add font-style and padding to header nav items

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-312
Test URLs:
Before:
After:
https://steri016-312-ch--shredit--stericycle.aem.live/en-us

STERI016-312: Update wizard form buttons styling

---

blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-312
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/hero
After:
https://steri016-326-badge-ch--shredit--stericycle.aem.live/drafts/conary/hero

STERI016-326: Update hero banner promo badge font size and line height

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-291
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/form
After:
https://steri016-291-ch--shredit--stericycle.aem.live/refresh-testing/form

STERI016-291: Update form.css splitbuttons with flexbox styles

---

blocks/simple-cta/simple-cta.css
blocks/simple-cta/simple-cta.js
scripts/aem.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-312
Test URLs:
Before:
After:
https://steri016-357-ch--shredit--stericycle.aem.live/en-us

Steri016 357 ch

---

blocks/banner/banner.css

Fix #788 
Test URLs:
- Before: 
- After: 
- https://banner-wrap-mobile--shredit--stericycle.aem.page/en-us

wrap words in mobile view

---

blocks/banner/banner.css
blocks/header/nav.css
blocks/header/utils.js
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-265
Test URLs:
Before:
After:
https://steri016-265-ch--shredit--stericycle.aem.live/en-us

STERI016-265: Update Notification banner styles

---

blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-229
Test URLs:
Before:
After:
https://steri016-229-ch--shredit--stericycle.aem.live/en-us

STERI016-229: Update checkboc wizard style

---

blocks/flip-cards/flip-cards.css
blocks/flip-cards/flip-cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-314
Test URLs:
- Before: 
- After: 
- https://steri016-314-flip-card-am--shredit--stericycle.aem.live/refresh-testing/flip-cards

STERI016-314: Flip Card Tiles - Allow author to choose different CTA button variations

---

blocks/form/submit.js

Test URLs:
- Before: 
- After: 
- https://finalfix--shredit--stericycle.aem.page/

final forms analytics fix

---

blocks/form/submit.js

Fix #796 
Test URLs:
- Before: 
- After: 
- https://issue796--shredit--stericycle.aem.page/

add google ad word id in form submit data

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-402
Test URLs:
Before:
After:
https://steri016-402-ch--shredit--stericycle.aem.live/en-us

STERI016-402: Update searchbar spacing

---

blocks/form/submit.js

Test URLs:
- Before: 
- After: 
- https://forms--shredit--stericycle.aem.page/

minor: added currentPagePath for filtering in excel

---

blocks/header/nav.css
blocks/header/utils.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-409
Test URLs:
Before:
After:
https://steri016-409-ch--shredit--stericycle.aem.live/en-us

STERI016-409: Fix header ctas

---

blocks/offer-box/offer-box.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-411
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/tools/sidekick/blocks/offerbox
After:
https://steri016-411-ch--shredit--stericycle.aem.live/tools/sidekick/blocks/offerbox

STERI016-411: Fix header card alignment

---

en-us/sitemap.xml

Test URLs:
- Before: 
- After: 
- https://sitemap--shredit--stericycle.aem.page/

Add sitemap manually

---

blocks/flip-cards/flip-cards.css
blocks/flip-cards/flip-cards.js
blocks/flip-cards/utils.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-315
Test URLs:
- Before: 
- After: 
- https://steri016-315-flip-card-am--shredit--stericycle.aem.live/refresh-testing/flip-cards

STERI016-315: Flip Card Tiles - Update the card content to be top aligned

---

blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-418
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/one-time-shredding-redesign
After:
https://steri016-418-ch--shredit--stericycle.aem.live/refresh-testing/one-time-shredding-redesign

STERI016-418: Fix hero banner content width

---

scripts/delayed.js
scripts/scripts.js

Test URLs:
- Before: 
- After: 
- https://analytics-go-live--shredit--stericycle.aem.page/

Prepare go-live analytics

---

blocks/form/constant.js

Test URLs:
- Before: 
- After: 
- https://rcaptachakey--shredit--stericycle.aem.page/

updating recaptcha key

---

blocks/form/form.css
blocks/icon-list/icon-list.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-419
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/one-time-shredding-redesign
After:
https://steri016-419-ch--shredit--stericycle.aem.live/refresh-testing/one-time-shredding-redesign

STERI016-419: Fix columns with form content width

---

blocks/footer/footer.css
blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-396
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/en-us
- After: 
- https://steri016-396-footer--shredit--stericycle.aem.live/refresh-testing/en-us

STERI016-396: Header/ Footer Alignment 

---

blocks/simple-cta/simple-cta.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-420
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/drafts/conary/simple-cta-image
After:
https://steri016-420-ch--shredit--stericycle.aem.live/drafts/conary/simple-cta-image

Steri016 420 ch

---

blocks/flip-cards/flip-cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-394
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/about
- After: 
- https://steri016-394-flip-am--shredit--stericycle.aem.live/en-us/about

STERI016-394: Flip Card - Content on Description Field(Bugfix)

---

blocks/form/form.css
blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-418
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/hero
After:
https://steri016-418-form-ch--shredit--stericycle.aem.live/refresh-testing/hero

STERI016-418: Fix hero banner  form content width padding

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-409
Test URLs:
Before:
After:
https://steri016-409-header-ch--shredit--stericycle.aem.live/en-us

STERI016-409: Fix header icon

---

blocks/featuretable/featuretable.css
blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-427
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/tools/sidekick/blocks/featuretable
After:
https://steri016-427-ch--shredit--stericycle.aem.live/tools/sidekick/blocks/featuretable

STERI016-427: Fix table borders

---

styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-355
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.page/en-us
- After: 
- https://steri016-355-regression-am--shredit--stericycle.aem.live/en-us

STERI016-355-regression: [Regression] handle problematic utility classes inherited from main code branch

---

blocks/paginated-list/paginated-list.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-434
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/about/news-articles
- After: 
- https://steri016-434-articles-am--shredit--stericycle.aem.live/en-us/about/news-articles

STERI016-434: New Articles - The page is being displayed without styles

---

blocks/modal/modal.css

Fix #829 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/service-locations/akron
- After: 
- https://issue829--shredit--stericycle.aem.page/en-us/service-locations/akron

fix margin in modal pop-up

---

blocks/form/form.css
blocks/header/nav.css
blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-433
Test URLs:
Before:
After:
https://steri016-433-ch--shredit--stericycle.aem.live/en-us

STERI016-433: Update radio button styling

---

blocks/flip-cards/flip-cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-314
Test URLs:
- Before: 
- After: 
- https://steri016-314-flip-card-tiles-am--shredit--stericycle.aem.live/refresh-testing/flip-cards

STERI016-314: Flip Card Tiles - Allow author to choose different CTA button variations(Bugfix)

---

blocks/offer-box/offer-box.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-450
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/offerbox
After:
https://steri016-450-ch--shredit--stericycle.aem.live/refresh-testing/offerbox

STERI016-450: Fix offerbox three column layout

---

blocks/form/form.css

Fix #832 
Test URLs:
- Before: 
- https:/main--shredit--stericycle.aem.page/en-us/marketing/protect-your-business-shred-it-hard-drive-destruction 
- After: 
- https://issue832--shredit--stericycle.aem.page/en-us/marketing/protect-your-business-shred-it-hard-drive-destruction

align form on top in mobile layout

---

blocks/clickable-columns/clickable-columns.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-356
Test URLs:
- Before: 
- After: 
- https://steri016-356-regression-am--shredit--stericycle.aem.live/en-us

Steri016 356: [Regression] clickable-columns button-container

---

blocks/security-risk-assessment-tool/styles/shredit-styles.css
styles/styles.css

Fix #814 
Test URLs:
- Before: 
- After: 
- https://hide-recaptcha--shredit--stericycle.aem.page/en-us

hides recaptcha

---

blocks/quote/quote.css
blocks/simple-cta/simple-cta.css
templates/service-location-page/service-location-page.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-462
Test URLs:
Before: https://refresh-develop--shredit--stericycle.aem.live/en-us/service-locations/omaha
After: https://steri016-462-ch--shredit--stericycle.aem.live/en-us/service-locations/omaha

STERI016-462: Fix quote and simple cta layout issues

---

blocks/header/nav.css
blocks/header/utils.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-89
Test URLs:
Before:
After:
https://steri016-89-scroll-ch--shredit--stericycle.aem.live/en-us

STERI016-89: Fix scroll issue with alert banner

---

blocks/header/nav.css
blocks/simple-cta/simple-cta.css
styles/styles.css
templates/service-location-page/service-location-page.css
templates/service-location-page/service-location-page.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-462
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/en-us/service-locations/omaha
After:
https://steri016-462-flip-cards-ch--shredit--stericycle.aem.live/en-us/service-locations/omaha

Steri016 462 flip cards ch

---

blocks/hero-banner/hero-banner.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-436
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/refresh-testing/hero
After:
https://steri016-436-ch--shredit--stericycle.aem.live/refresh-testing/hero

STERI016-436: Add lists support to hero banner

---

blocks/columns/default.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-451
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices
- After: 
- https://steri016-451-alignment-am--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

STERI016-451: Alignment Issues - Why Choose Shred-it &

---

blocks/flip-cards/flip-cards.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-443
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/about
- After: 
- https://steri016-443-flip-am--shredit--stericycle.aem.live/en-us/about

STERI016-443: Flip card Block - Missing Title on Flip Card Block with External Destination Link

---

blocks/form/form.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-454
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices
- After: 
- https://steri016-454-modal-am--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

STERI016-454: Fix modal form and toggle button display issue.

---

blocks/header/alt-0-nav.js
blocks/header/alt-1-nav.js
blocks/header/nav.js
scripts/scripts.js
styles/styles.css

all possible nav alternates included as examples
Fix #834 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/en-us/marketing/document-destruction-service
- After: 
- https://fix-sticky--shredit--stericycle.aem.page/en-us/marketing/document-destruction-service
- https://fix-sticky--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding
- https://fix-sticky--shredit--stericycle.aem.page/en-us/marketing/hard-drive
- https://fix-sticky--shredit--stericycle.aem.page/en-us/marketing/25purge

globalize floating-contact

---

blocks/cards/cards.css
templates/service-location-page/service-location-page.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-462
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/en-us/service-locations/omaha
After:
https://steri016-462-cta-ch--shredit--stericycle.aem.live/en-us/service-locations/omaha

STERI016-462: Update CTA styling

---

styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-355
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service
- After: 
- https://steri016-355-issue-am--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

STERI016-355: [Regression] handle problematic utility classes inherited from main code branch(Bugfix)

---

blocks/header/alt-2-nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-460
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline
After:
https://steri016-460-ch--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline

STERI016-460: Update header cta height

---

blocks/cards/cards.css
blocks/footer/footer.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-452
Test URLs:
Before:
https://refresh-develop--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices
After:
https://steri016-452-ch--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

STERI016-452: Update gray color token

---

scripts/delayed.js
scripts/martech.js

Fix #862
Test URLs:
- Before: 
- After: 
- https://issue-862--shredit--stericycle.aem.page/

Integrate clarity tracking

---

blocks/form/form.css
blocks/form/form.js

Ticket: https://herodigital.atlassian.net/browse/STERI016-447
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/marketing/document-destruction-service
- After: 
- https://steri016-447-form-am--shredit--stericycle.aem.live/en-us/marketing/document-destruction-service

STERI016-447: Form - Button Toggle Rendering + Privacy Policy Link - Component Revamp

---

templates/service-location-page-2/service-location-page-2.js
templates/service-location-page/service-location-page.js

Fix for https://herodigital.atlassian.net/browse/STERI016-487
Test URLs:
Adding quotation marks:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/service-locations/omaha
- After: 
- https://steri016-487-fix-typos--shredit--stericycle.aem.page/en-us/service-locations/omaha
Fixing typos:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/service-locations/new-york
- After: 
- https://steri016-487-fix-typos--shredit--stericycle.aem.page//en-us/service-locations/new-york

Steri016 487 fix typos

---

blocks/form/constant.js

Fix #857 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/
- After: 
- https://issues-857--shredit--stericycle.aem.live/

recaptcha token based on domain

---

blocks/header/nav.js
scripts/scripts.js
styles/styles.css

Fix # [STERI016-494](https://herodigital.atlassian.net/browse/STERI016-494)
Test URLs:
- Before: 
- After: 
- https://steri016-494--shredit--stericycle.aem.live/en-us

Steri016 494

---

blocks/offer-box/offer-box.css

Fix # https://herodigital.atlassian.net/browse/STERI016-450
Test URLs:
- Before: 
- https://refresh-develop--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices
- After: 
- https://steri016-450-fixes--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

Steri016 450 fixes

---

blocks/header/nav.css

Ticket: https://herodigital.atlassian.net/browse/STERI016-500
Test URLs:
- Before: 
- After: 
- https://steri016-500-nav-am--shredit--stericycle.aem.live/en-us

STERI016-500: Nav - Search box input field

---

blocks/hero/hero.js

Ticket: https://herodigital.atlassian.net/browse/STERICMS-846
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/refresh-testing/offer
- After: 
- https://stericms-846-am--shredit--stericycle.aem.live/refresh-testing/offer

STERICMS-846-am: Update hero background color handling based on metadata

---

blocks/footer/footer.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-812
Test URLs:
- Before: 
- After: 
- https://stericms-812-header-am--shredit--stericycle.aem.live/en-us

STERICMS-812: Header/ Footer CTA Alignment

---

blocks/simple-cta/simple-cta.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-808
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/refresh-testing/hero
- After: 
- https://stericms-808-simple-am--shredit--stericycle.aem.live/refresh-testing/hero

STERICMS-808-simple-am: Simple CTA Panel - UAT issues

---

styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-824
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/refresh-testing/sections-features
- After: 
- https://stericms-824-section-am--shredit--stericycle.aem.live/refresh-testing/sections-features

STERICMS-824-section-am: Add an additional background.

---

blocks/facet-list/facet-list.css

Fix [STERICMS-818](https://herodigital.atlassian.net/browse/STERICMS-818)
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/drafts/conary/blog
- After: 
- https://stericms-818-blog-list-image--shredit--stericycle.aem.live/drafts/conary/blog

STERICMS-818 Adjusted image container width

---

blocks/icon-list/icon-list.css

Fix [STERICMS-852](https://herodigital.atlassian.net/browse/STERICMS-852)
Test URLs:
Before:
https://main--shredit--stericycle.aem.page/drafts/commercial-page-revamp/one-time-shredding-redesign
After:
https://stericms-852-ch--shredit--stericycle.aem.page/drafts/commercial-page-revamp/one-time-shredding-redesign

STERICMS-852: Update icon list CSS to set height to auto for better responsiveness

---

blocks/simple-cta/simple-cta.css

Fix [STERICMS-854](https://herodigital.atlassian.net/browse/STERICMS-854)
Test URLs:
Before:
https://main--shredit--stericycle.aem.page/drafts/commercial-page-revamp/one-time-shredding-redesign
After:
https://stericms-854-ch--shredit--stericycle.aem.page/drafts/commercial-page-revamp/one-time-shredding-redesign

Stericms 854 ch

---

blocks/banner/banner.css
styles/styles.css

Fix [STERICMS-809](https://herodigital.atlassian.net/browse/STERICMS-809)
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/refresh-testing/hero
- After: 
- https://stericms-809-notification-banner--shredit--stericycle.aem.page/refresh-testing/hero

STERICMS-809 Adjusted padding and width for the notification banner

---

blocks/footer/footer.css
blocks/footer/footer.js

Fix [STERICMS-814](https://herodigital.atlassian.net/browse/STERICMS-814)
Test URLs:
Before:
https://main--stericycle-shared--aemsites.aem.page/drafts/rene/shred-it-document-destruction-inline
After:
https://stericms-814-sem-page-footer--stericycle-shared--aemsites.aem.page/drafts/rene/shred-it-document-destruction-inline

Stericms 814 sem page footer

---

blocks/columns/columns.js
blocks/columns/default.js
blocks/form/form.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-859
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/en-us/email/paper-shredding-services
- After: 
- https://stericms-859-sid-am--shredit--stericycle.aem.live/en-us/email/paper-shredding-services

STERICMS-859: SID - New SEM Page - Content Rendering Issues

---

blocks/columns/default.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-860
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/commercial-page-revamp/mobile-shredding-redesign
- After: 
- https://stericms-860-column-am--shredit--stericycle.aem.live/drafts/commercial-page-revamp/mobile-shredding-redesign

STERICMS-860: Column Images - Rounded Corners

---

blocks/hero-banner/hero-banner.css
blocks/hero-banner/hero-banner.js

Ticket: https://herodigital.atlassian.net/browse/STERICMS-865
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/drafts/commercial-page-revamp/community-shredding-redesign
- After: 
- https://stericms-865-am--shredit--stericycle.aem.live/drafts/commercial-page-revamp/community-shredding-redesign

STERICMS-865: Hero Banner - No Promo and Margins

---

blocks/cards/cards.css
blocks/form/components/radio/radio.css
blocks/form/form.css
blocks/header/nav.css
styles/styles.css

Fix [STERICMS-864](https://herodigital.atlassian.net/browse/STERICMS-864)
Test URLs:
Before:
https://main--shredit--stericycle.aem.page/drafts/commercial-page-revamp/residential-shredding-redesign
After:
https://stericms-864-ch--shredit--stericycle.aem.page/drafts/commercial-page-revamp/residential-shredding-redesign

STERICMS-864: Update box-shadow syntax in cards.css for compatibility

---

blocks/download/download.css
blocks/download/download.js

Fix [STERICMS-845](https://herodigital.atlassian.net/browse/STERICMS-845)
Test URLs:
Before:
https://main--shredit--stericycle.aem.page/drafts/conary/how-to-choose-a-shredding-company
After:
https://stericms-845-ch--shredit--stericycle.aem.page/drafts/conary/how-to-choose-a-shredding-company

STERICMS-845: Enhance download block styling

---

blocks/facet-list/facet-list.css
blocks/facet-list/facet-list.js
blocks/form/form.css

Fix [STERICMS-827](https://herodigital.atlassian.net/browse/STERICMS-827)
Test URLs:
Before:
https://main--shredit--stericycle.aem.page/en-us/resource-center
After:
https://stericms-827-ch--shredit--stericycle.aem.page/en-us/resource-center

STERICMS-827: Enhance facet list styles and functionality

---

blocks/hero/hero.css
styles/styles.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-875
Test URLs:
- Before: 
- After: 
- https://stericms-875-mobile-am--shredit--stericycle.aem.live/en-us

STERICMS-875: EDS - Mobile Rendering Issues

---

blocks/icon-list/icon-list.css
blocks/icon-list/icon-list.js

Fix [STERICMS-862](https://herodigital.atlassian.net/browse/STERICMS-862)
Test URLs:
Before:
https://main--shredit--stericycle.aem.page//drafts/commercial-page-revamp/home
After:
https://stericms-862-v2-ch--shredit--stericycle.aem.page/drafts/commercial-page-revamp/home

STERICMS-862: Enhance icon list styling and functionality for two-column layout

---

blocks/form/form.css

Fix issue [STERICMS-871](https://herodigital.atlassian.net/browse/STERICMS-871)
Test URLs: 
- Before:  https://main--shredit--stericycle.aem.page/drafts/commercial-page-revamp/hard-drive-destruction-redesign 
- After: https://stericms-871-policy-link-color--stericycle-shared--aemsites.aem.page/drafts/commercial-page-revamp/hard-drive-destruction-redesign

Stericms 871 policy link color

---

blocks/icon-list/icon-list.css

Ticket: https://herodigital.atlassian.net/browse/STERICMS-882
Test URLs:
- Before: 
- https://main--stericycle-shared--aemsites.aem.live/drafts/commercial-page-revamp/drop-off-redesign
- After: 
- https://stericms-882-icon-am--shredit--stericycle.aem.live/drafts/commercial-page-revamp/drop-off-redesign

STERICMS-882: Icon list - No Form Layout - 3 Column

---

blocks/hero-banner/hero-banner.css
en-us/sitemap.xml

Ticket: https://herodigital.atlassian.net/browse/STERICMS-884
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.live/drafts/commercial-page-revamp/one-time-shredding-redesign
- After: 
- https://stericms-844-banner-dd--shredit--stericycle.aem.live/drafts/commercial-page-revamp/one-time-shredding-redesign

STERICMS-844: Hero Banner - CTA Spacing

---

blocks/columns/default.css

Ticket: [https://herodigital.atlassian.net/browse/STERICMS-881](https://herodigital.atlassian.net/browse/STERICMS-881)
Test URLs:
- Before (Last Steps component in the page):
- [https://main--shredit--stericycle.aem.live/refresh-testing/columns-features](https://main--shredit--stericycle.aem.page/refresh-testing/columns-features)
- After (Last Steps component in the page):
- [https://stericms-881-steps-secondary--shredit--stericycle.aem.live/refresh-testing/columns-features](https://stericms-881-steps-secondary--shredit--stericycle.aem.live/refresh-testing/columns-features)

STERICMS-881: Add steps-secondary variant styles to columns

---

blocks/header/utils.js

no ticket
This update makes the nav work for both sharepoint and DA content
Test URLs:
- Before: 
- https://da--shred-it--stericycle.aem.page/
- After: 
- https://da-us-nav--shred-it--stericycle.aem.page/

support sharepoint or DA markup in nav

---

blocks/blog-filter/blog-filter.js
blocks/facet-list/facet-list.js
blocks/paginated-list/paginated-list.js
blocks/search/search.js
blocks/service-location-list/service-location-list.js
blocks/service-location-map/service-location-map.js
scripts/ffetch.js
scripts/scripts.js

Fix #STER-10
Test URLs:
- Before:
- https://main--shred-it--stericycle.aem.live/en-us/search?searchQuery=business
- https://main--shred-it--stericycle.aem.live/en-us/blog
- After:
- https://ster-10--shred-it--stericycle.aem.live/en-us/search?searchQuery=business
- https://ster-10--shred-it--stericycle.aem.live/en-us/blog

Ster 10 - refactor to support new indexes in DA

---

blocks/banner/banner.css
blocks/banner/banner.js

Added a new class that will stop the privacy banner from creating a blue line in the middle of the page
Fix #927 
Test URLs:
- Before: 
- After: 
- https://stericms-876-privacy-banner--shredit--stericycle.aem.page/

STERICMS-876: add transparent background for fixed bottom banner containers

---

blocks/header/alt-3-nav.css
blocks/header/alt-3-nav.js
blocks/header/utils.js

Fix # [STERICMS-886](https://herodigital.atlassian.net/browse/STERICMS-886) 
Test URLs:
- Before: 
- https://main--shredit--stericycle.aem.page/refresh-testing/home
- After: 
- https://stericms-886-new-header--shredit--stericycle.aem.page/refresh-testing/home

STERICMS-886 - Add header navigation and styling for alt-3 layout

---

blocks/hero-banner/hero-banner.js
tools/importer/blog.js

Jira: https://herodigital.atlassian.net/jira/software/c/projects/STER/boards/1849?selectedIssue=STER-63
Test URLs:
Before: https://main--shred-it--stericycle.aem.page/drafts/gabriel/blog/are-you-shredding-these-documents-you-should-be
After https://ster-63-blogs-update-to-import-template--shred-it--stericycle.aem.page/drafts/gabriel/blog/are-you-shredding-these-documents-you-should-be

STER-63: Update images rule to use the prod domain isted of local

---

tools/sitemap-generation/generate-sitemap.js
tools/sitemap-generation/index.js

Test URLs:
- Before: 
- https://da--shred-it--stericycle.aem.page/
- After: 
- https://da-sitemap--shred-it--stericycle.aem.page/

DA Sitemap

---

blocks/faq/faq.js
blocks/hero-banner/hero-banner.js

Fix #STER-69
Test URLs:
- Before: 
- https://main--shred-it--stericycle.aem.live/en-us/resource-center/faq
- After: 
- https://ster-69--shred-it--stericycle.aem.live/en-us/resource-center/faq

fix video embeds in faq block for da, remove console.log

---

tools/importer/resource-center.js

Url test: https://main--shred-it--stericycle.aem.page/drafts/gabriel/resource-centre/en-ca/resource-centre/info-sheets/5-important-steps-to-enhance-data-protection-in-your-business

Ster 64 resource center import template

---

scripts/delayed.js

Test URLs:
- Before: 
- https://main--shred-it--stericycle.aem.live/en-us
- After: 
- https://zoominfo--shred-it--stericycle.aem.live/en-us

add zoominfo script in delayed.js.

---

blocks/hero-banner/hero-banner.css
styles/styles.css

Added extra class
URL for testing:
- https://ster-74-autoring-bugs-4-bullets--shred-it--stericycle.aem.live/fr-ca/economisez-25
- https://ster-74-autoring-bugs-4-bullets--stericycle-shared--aemsites.aem.page/

Added extra class to change the layout to bullets

---

tools/block-updater/block-updater.js

Test URLs:
- Before: 
- https://main--shred-it--stericycle.aem.live/
- After: 
- https://block-updater-fix--shred-it--stericycle.aem.live/

use auth token.

---

templates/blog-page/blog-page.js

Test URLs:
- Before: 
- https://main--shred-it--stericycle.aem.live/en-ca/blog/what-goes-in-shredding-bin
- After: 
- https://remove-blog-breadcrumbs--shred-it--stericycle.aem.live/en-ca/blog/what-goes-in-shredding-bin

per client remove breadcrumb above blog content

---

blocks/form/lib/forms-common.js
blocks/form/submit.js

send uppercase country code for canada & use placeholders for radio values
Fix https://herodigital.atlassian.net/browse/STER-97
Test URLs:
- Before: 
- https://canada-da--shred-it--stericycle.aem.page/
- After: 
- https://ster-97--shred-it--stericycle.aem.page/

Canada forms updates

---

scripts/martech.js

Test URLs:
- Before: 
- https://main--shred-it--stericycle.aem.page/
- After: 
- https://analytics-country--shred-it--stericycle.aem.page/

update country in data layer correctly

---

blocks/search/search.js

Test URLs:
- Before: 
- https://canada-da--shred-it--stericycle.aem.page/fr-ca/search
- After: 
- https://search-translation--shred-it--stericycle.aem.page/fr-ca/search

fix placeholder logic for searchbar
